using PokerRanges.Core.Cards;

namespace PokerRanges.Core.Ranges;

/// <summary>
/// The 169 starting hands ordered by their equity against a hand drawn at random — the same
/// yardstick every equity tool uses for "top X%".
/// </summary>
/// <remarks>
/// The table is shipped as data rather than measured at startup, for precision rather than speed.
/// Neighbouring hands are about 0.003 apart in equity, so telling them apart needs a standard error
/// well under that, i.e. of the order of a million samples per hand — minutes of work, on every
/// launch, to rediscover a constant of the game. It is regenerated by
/// <c>PreflopHandStrengthGenerator</c> in the test project, and a test re-measures a sample of it to
/// prove the shipped ranks still hold.
/// </remarks>
public sealed class PreflopHandStrength : IPreflopHandStrength
{
    /// <summary>Below this, floating-point crumbs are not worth a cell of their own.</summary>
    private const double BudgetTolerance = 1e-9;

    private static readonly (string Notation, double Equity)[] Measured = MeasuredTable();

    private readonly RankedHandClass[] _ordered;

    public PreflopHandStrength()
    {
        _ordered = [.. Measured.Select(entry => new RankedHandClass(HandClass.Parse(entry.Notation), entry.Equity))];
    }

    public IReadOnlyList<RankedHandClass> Ordered => _ordered;

    public HandRange TopPercent(double percent)
    {
        double budget = Math.Clamp(percent, 0, 100) / 100.0 * HoleCards.Count;
        HandRangeBuilder builder = new();

        foreach (RankedHandClass ranked in _ordered)
        {
            if (budget <= BudgetTolerance)
            {
                break;
            }

            int combos = ranked.HandClass.CombinationCount;

            if (budget >= combos)
            {
                builder.Set(ranked.HandClass, 1);
                budget -= combos;
                continue;
            }

            // The hand straddling the cut-off is thinned across every one of its combos rather than
            // a few of them: no suit is favoured, the total stays exact, and the notation stays
            // readable as "T9o:0.42" instead of a list of individual combos.
            builder.Set(ranked.HandClass, budget / combos);
            budget = 0;
        }

        return builder.Build();
    }

    private static (string, double)[] MeasuredTable() =>
    [
        new("AA", 0.8522),
        new("KK", 0.8242),
        new("QQ", 0.7988),
        new("JJ", 0.7744),
        new("TT", 0.7501),
        new("99", 0.7204),
        new("88", 0.6924),
        new("AKs", 0.6712),
        new("77", 0.6621),
        new("AQs", 0.6619),
        new("AJs", 0.6539),
        new("AKo", 0.6524),
        new("ATs", 0.6460),
        new("AQo", 0.6438),
        new("AJo", 0.6364),
        new("KQs", 0.6347),
        new("66", 0.6328),
        new("A9s", 0.6283),
        new("ATo", 0.6274),
        new("KJs", 0.6258),
        new("A8s", 0.6193),
        new("KTs", 0.6176),
        new("KQo", 0.6142),
        new("A7s", 0.6097),
        new("A9o", 0.6074),
        new("KJo", 0.6067),
        new("55", 0.6039),
        new("QJs", 0.6024),
        new("K9s", 0.5997),
        new("A6s", 0.5990),
        new("A5s", 0.5989),
        new("A8o", 0.5987),
        new("KTo", 0.5961),
        new("QTs", 0.5933),
        new("A4s", 0.5903),
        new("A7o", 0.5888),
        new("K8s", 0.5822),
        new("A3s", 0.5815),
        new("QJo", 0.5815),
        new("K9o", 0.5777),
        new("A5o", 0.5761),
        new("Q9s", 0.5761),
        new("K7s", 0.5760),
        new("A6o", 0.5759),
        new("JTs", 0.5757),
        new("A2s", 0.5735),
        new("QTo", 0.5727),
        new("44", 0.5705),
        new("K6s", 0.5673),
        new("A4o", 0.5666),
        new("K8o", 0.5609),
        new("Q8s", 0.5603),
        new("A3o", 0.5594),
        new("K5s", 0.5579),
        new("J9s", 0.5562),
        new("Q9o", 0.5534),
        new("JTo", 0.5529),
        new("K7o", 0.5515),
        new("A2o", 0.5499),
        new("K4s", 0.5479),
        new("K6o", 0.5420),
        new("Q7s", 0.5415),
        new("J8s", 0.5411),
        new("K3s", 0.5406),
        new("T9s", 0.5401),
        new("33", 0.5377),
        new("Q6s", 0.5363),
        new("Q8o", 0.5363),
        new("K5o", 0.5329),
        new("J9o", 0.5328),
        new("K2s", 0.5312),
        new("Q5s", 0.5284),
        new("K4o", 0.5249),
        new("T8s", 0.5233),
        new("J7s", 0.5230),
        new("Q7o", 0.5174),
        new("Q4s", 0.5174),
        new("K3o", 0.5154),
        new("J8o", 0.5145),
        new("T9o", 0.5140),
        new("Q6o", 0.5124),
        new("Q3s", 0.5092),
        new("98s", 0.5092),
        new("J6s", 0.5080),
        new("T7s", 0.5066),
        new("22", 0.5048),
        new("K2o", 0.5046),
        new("Q5o", 0.5016),
        new("Q2s", 0.5014),
        new("J5s", 0.4997),
        new("T8o", 0.4972),
        new("J7o", 0.4958),
        new("Q4o", 0.4921),
        new("J4s", 0.4905),
        new("97s", 0.4904),
        new("T6s", 0.4902),
        new("Q3o", 0.4837),
        new("J3s", 0.4825),
        new("98o", 0.4801),
        new("T7o", 0.4793),
        new("87s", 0.4792),
        new("J6o", 0.4789),
        new("J2s", 0.4752),
        new("96s", 0.4750),
        new("Q2o", 0.4737),
        new("T5s", 0.4720),
        new("J5o", 0.4718),
        new("T4s", 0.4663),
        new("J4o", 0.4629),
        new("86s", 0.4626),
        new("97o", 0.4621),
        new("T6o", 0.4602),
        new("95s", 0.4589),
        new("T3s", 0.4566),
        new("76s", 0.4527),
        new("J3o", 0.4521),
        new("87o", 0.4492),
        new("T2s", 0.4487),
        new("85s", 0.4457),
        new("96o", 0.4449),
        new("T5o", 0.4427),
        new("J2o", 0.4424),
        new("94s", 0.4388),
        new("75s", 0.4366),
        new("T4o", 0.4356),
        new("86o", 0.4332),
        new("93s", 0.4332),
        new("65s", 0.4301),
        new("95o", 0.4274),
        new("84s", 0.4267),
        new("T3o", 0.4263),
        new("92s", 0.4245),
        new("76o", 0.4225),
        new("74s", 0.4171),
        new("T2o", 0.4168),
        new("85o", 0.4147),
        new("54s", 0.4139),
        new("64s", 0.4123),
        new("83s", 0.4083),
        new("94o", 0.4063),
        new("75o", 0.4057),
        new("82s", 0.4024),
        new("93o", 0.4016),
        new("65o", 0.4000),
        new("73s", 0.3997),
        new("63s", 0.3961),
        new("53s", 0.3958),
        new("84o", 0.3942),
        new("92o", 0.3921),
        new("43s", 0.3870),
        new("74o", 0.3845),
        new("72s", 0.3830),
        new("54o", 0.3820),
        new("64o", 0.3801),
        new("52s", 0.3794),
        new("62s", 0.3770),
        new("83o", 0.3735),
        new("42s", 0.3683),
        new("82o", 0.3679),
        new("73o", 0.3670),
        new("53o", 0.3622),
        new("63o", 0.3608),
        new("32s", 0.3596),
        new("43o", 0.3514),
        new("72o", 0.3458),
        new("52o", 0.3434),
        new("62o", 0.3411),
        new("42o", 0.3325),
        new("32o", 0.3231),
    ];
}
